"""Auto-generated by build_capstone_checkpoints.py (Checkpoint 1.1 starter).
Jupytext-style cell markers (# %% / # %% [markdown]) — runnable as a
plain script AND openable as cells in VS Code / PyCharm / Jupytext.
"""

# %% [markdown]
# # Capstone Checkpoint 1.1 — Evaluating When Retrieval is Required
# **MO-LLM Module 1 / Required Capstone Checkpoint (120 minutes)**
#
# ## What this checkpoint is
#
# This is the first checkpoint of your **capstone project**, which you build across the whole program. Here you establish the **no-retrieval baseline**: you test how a plain LLM behaves on your chosen scenario *before* adding any retrieval, document where it falls short, and argue whether (and why) retrieval is needed.
#
# This mirrors **Lab 1.1** — where you probed an LLM for five failure modes — but now applied to the realistic corpus you'll build your system on. The deliverable is a **400-550-word written analysis** (see the final section); this notebook is the tool that produces the evidence for that writeup.
#
# **Learning outcomes (same as Lab 1.1):**
# 1. Implement a basic application that interacts with an LLM via an API.
# 2. Explain key limitations of LLMs that affect reliability and grounding.
# 3. Determine when external retrieval is required for a given use case.
# 4. Explain how the specificity, relevance, and accuracy of retrieved information affect output quality.
#
# **Important:** This checkpoint uses **no retrieval and no document parsing**. You are deliberately testing the LLM *without* access to your corpus, so you can see what it gets wrong. Loading and indexing your documents comes in Checkpoint 2.1.

# %% [markdown]
# ## Step 1 — Choose your scenario (keep it for the whole program)
#
# Pick **one** of the two capstone scenarios. You will use the same scenario for every checkpoint from here on.
#
# | Scenario | Corpus | What your system must eventually do |
# |---|---|---|
# | **Research Paper Navigator** | ~150 research-paper PDFs (`Labs/CapstoneDatasets/ResearchPapers/`) | Answer questions about the papers and **quote them directly**; handle single-paper and cross-paper questions (compare ideas, trace how an idea evolved); maintain conversation history. |
# | **Wikipedia Retrieval Engine** | ~2,400 Wikipedia HTML articles (`Labs/CapstoneDatasets/Wikipedia/`) | Answer questions about significant figures/places and **back answers with direct quotes** from the articles; handle single-article and cross-article questions; maintain conversation history. |
#
# Both model the same real-world pattern: a chat interface over a large body of complex documents where answers must be **grounded and quotable**, not just fluent.
#
# Set `SCENARIO` below to the one you chose.

# %% [markdown]
# ## Setup (~5 min)
#
# 1. **Python 3.11 or 3.12.**
# 2. `pip install langchain-openai langchain-core python-dotenv`
# 3. Get a free OpenRouter key at <https://openrouter.ai/keys> (this checkpoint uses the paid gpt-5.4-mini chat model — covered by your course credits — and no embeddings).
# 4. Create a `.env` file next to this script: `OPENROUTER_API_KEY=sk-or-v1-...`
#
# You do **not** need to download or parse the corpus for this checkpoint — you only need to look at a few documents to write realistic prompts (open a couple of PDFs/articles in the dataset folder by hand).

# %%
from __future__ import annotations

import warnings
warnings.filterwarnings("ignore")

import os
from datetime import datetime
from pathlib import Path
from typing import Any

from dotenv import load_dotenv
from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import ChatOpenAI

# %%
OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"
LLM_MODEL = "openai/gpt-5.4-mini"  # latest small OpenAI model, fast; covered by course credits
TEMPERATURE = 0.2
LOG_PATH = Path.cwd() / "checkpoint_1_1_responses.log"

# === SET THIS to your chosen scenario ===
SCENARIO = "research_papers"   # "research_papers" or "wikipedia"

SYSTEM_PROMPT = (
    "You are a helpful research assistant. Answer the user's question as "
    "accurately as you can. When you reference a specific document, quote "
    "from it directly. If you are not certain, say so rather than guessing."
)

# %%
def check_api_key() -> str:
    load_dotenv()
    key = os.getenv("OPENROUTER_API_KEY")
    if not key:
        raise RuntimeError(
            "OPENROUTER_API_KEY not set. Grab a free key at "
            "https://openrouter.ai/keys, put it in a .env file next to this "
            "script, and rerun."
        )
    return key


def build_chain() -> Any:
    """Baseline LLM chain — no retrieval. Same pattern as Lab 1.1."""
    llm = ChatOpenAI(
        model=LLM_MODEL,
        temperature=TEMPERATURE,
        api_key=check_api_key(),
        base_url=OPENROUTER_BASE_URL,
    )
    prompt = ChatPromptTemplate.from_messages([
        ("system", SYSTEM_PROMPT),
        ("human", "{question}"),
    ])
    return prompt | llm


def ask(chain: Any, question: str) -> str:
    resp = chain.invoke({"question": question})
    return resp.content if hasattr(resp, "content") else str(resp)


def log_response(scenario: str, prompt: str, response: str) -> None:
    ts = datetime.now().isoformat(timespec="seconds")
    entry = (
        f"[{ts}]  SCENARIO={scenario}  MODEL={LLM_MODEL}\n"
        f"PROMPT:   {prompt}\n"
        f"RESPONSE: {response}\n"
        f"{'-' * 72}\n"
    )
    with LOG_PATH.open("a", encoding="utf-8") as fh:
        fh.write(entry)

# %% [markdown]
# ## Step 2 — Baseline probe prompts (provided examples)
#
# Below are example prompts for each scenario. They deliberately ask about **specific content in your corpus** and demand **direct quotes** — exactly what a grounded system must do, and exactly what a plain LLM struggles with. A no-retrieval model will tend to:
#
# - **hallucinate** specifics (fabricate a paper's results, a date, a quote),
# - **hedge** ("I don't have access to that document"),
# - or give a **generic** answer that doesn't actually quote the source.
#
# These three behaviors are your evidence that retrieval is required. Read the responses critically — a fluent answer is not necessarily a correct one.

# %%
# Example baseline prompts per scenario. These reference REAL documents in the
# capstone datasets so you can check the model's answers against the source.
EXAMPLE_PROMPTS = {
    "research_papers": [
        # Asks for a specific finding from a specific paper in the collection.
        "In the paper 'The Counterfeit Conundrum: Can Code Language Models "
        "Grasp the Nuances of Their Incorrect Generations?' (Gu et al., ACL "
        "2024), what is the main finding about how code models perceive their "
        "own incorrect generations? Quote the relevant sentence.",
        # Asks to compare across papers — impossible without the corpus.
        "Compare how Solar-Lezama's 'The Sketching Approach to Program "
        "Synthesis' and other program-synthesis papers in this collection "
        "define the synthesis problem. Cite each paper.",
        # Asks for a verbatim quote — a no-retrieval model cannot reliably do this.
        "Quote, word for word, the first sentence of the abstract of "
        "'The Sketching Approach to Program Synthesis'.",
    ],
    "wikipedia": [
        # Asks for a current fact that may be stale in the model's training.
        "According to the Wikipedia article on the 100 meters, what is the "
        "current men's world record, who holds it, and when was it set? "
        "Quote the article.",
        # Asks for a verbatim quote from a specific article.
        "Quote the opening sentence of the Wikipedia article titled "
        "'13 (2010 film)'.",
        # Asks for an aggregated answer across articles.
        "List three significant events recorded in the Wikipedia article for "
        "the year 1580, quoting the article for each.",
    ],
}

# %% [markdown]
# ## Step 3 — Add your own probe prompts (TODO)
#
# The examples are a starting point. **Your turn:** write three of your own prompts for the scenario you chose. Good probes for this checkpoint:
#
# - Ask about a **specific fact** that lives in exactly one document in your corpus (open a paper/article and pick something concrete).
# - Ask for a **verbatim quote** from a named source — watch whether the model fabricates one.
# - Ask a **cross-document** question (compare two papers, or aggregate across articles).
# - Ask something **outside** the corpus to see whether the model admits it doesn't know.
#
# Return a list of prompt strings. Look at a few real documents in `Labs/CapstoneDatasets/` first so you can check the answers against ground truth.

# %%
def my_probe_prompts() -> list[str]:
    """Return 3-5 of YOUR OWN baseline prompts for your chosen scenario.

    TODO — your turn. See the guidance above. Each item is a prompt string.
    Open a few real documents in Labs/CapstoneDatasets/ so you can judge
    whether the model's answers are accurate.

    Delete the raise NotImplementedError line once your code works.
    """
    raise NotImplementedError("my_probe_prompts() — see the TODO above.")

# %% [markdown]
# ## Step 4 — Run the baseline probes and capture the evidence
#
# This runs the example prompts plus your own through the **no-retrieval** LLM and logs every prompt/response to `checkpoint_1_1_responses.log`. Read each answer against the real document (open it in the dataset folder) and classify what you see: hallucination, hedge, generic-but-unsourced, or correct.

# %%
def run_probes() -> None:
    check_api_key()
    chain = build_chain()
    prompts = EXAMPLE_PROMPTS.get(SCENARIO, []) + my_probe_prompts()

    print(f"Capstone Checkpoint 1.1 — baseline (no retrieval)")
    print(f"Scenario: {SCENARIO}  |  Model: {LLM_MODEL}")
    print(f"Logging to: {LOG_PATH.name}\n")

    for i, prompt in enumerate(prompts, start=1):
        print("=" * 72)
        print(f"PROMPT {i}/{len(prompts)}: {prompt[:90]}...")
        try:
            answer = ask(chain, prompt)
        except Exception as e:
            print(f"  API error: {e}")
            continue
        print(f"\nRESPONSE:\n{answer}\n")
        log_response(SCENARIO, prompt, answer)

    print("=" * 72)
    print(
        "Done. Now READ each response against the real document. For each, "
        "note: did the model hallucinate, hedge, give a generic unsourced "
        "answer, or get it right? This is the evidence for your write-up."
    )


run_probes()

# %% [markdown]
# ## Step 5 — Your written analysis (the graded deliverable)
#
# The checkpoint deliverable is a **500-750 word written submission**, not code. Using the evidence in `checkpoint_1_1_responses.log`, address each of these (this is the required structure from the assignment):
#
# 1. **Describe your scenario** and the types of questions/tasks the system must support.
# 2. **Provide examples** of prompts and the model's outputs (paste 2-3 telling ones from your log).
# 3. **Identify key limitations** in the responses (hallucination, missing information, inconsistency, inability to quote).
# 4. **Describe patterns** you observed in model behavior.
# 5. **Explain whether retrieval is required** for this scenario and why.
# 6. **Describe what information** would need to be retrieved.
# 7. **Explain why precision and relevance** of retrieved information matter — and how these choices affect reliability and user trust.
#
# Focus on clear reasoning supported by specific examples. You'll revisit and refine this as you build the system in later checkpoints.
